### ISSUE TITLE
[perf] Performance improvements

### ISSUE THREAD

**Issue by pascaliske** [pascaliske/pascal-iske.de#8]
- [x] Check prod bundles and decrease their size ([webpack-visualizer](https://github.com/chrisbateman/webpack-visualizer), [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer))
- [x] Prerender the app at build time (#31)
- [x] Automatically measure performance at build time (#32)
- [x] Automatically measure bundle sizes at build time (#33)
